### ISSUE TITLE
Why is event listener used? 

### ISSUE THREAD

**Issue by ViktorParakhonia** [Wildcorsair/redmine-helper#4]
There is no entity, form just returns array by getData() so you can add issue_id from action request parameter
 https://github.com/Wildcorsair/redmine-helper/blob/0e5b7c5a0b430084fe05240baeb052215789b6e0/src/AppBundle/Form/TimeLogType.php#L58

**Comment by Wildcorsair** [comment]
Fixed. Event listener was removed.
