### ISSUE TITLE
There is performance leak redmine client pulled projects twice

### ISSUE THREAD

**Issue by ViktorParakhonia** [Wildcorsair/redmine-helper#5]
https://github.com/Wildcorsair/redmine-helper/blob/0e5b7c5a0b430084fe05240baeb052215789b6e0/src/AppBundle/Controller/ProjectController.php#L32

**Comment by Wildcorsair** [comment]
This form was removed. Fixed.
First I realized the list of projects as a drop-down list, but then changed my mind, but the form remained.
